name: qp
channels:
  - conda-forge
  - salilab
  - defaults
dependencies:
  - python=3.8
  - biopython
  - click
  - matplotlib
  - modeller
  - numpy
  - pandas
  - pyyaml
  - requests
  - scikit-learn
  - scipy
  - seaborn
  - tqdm