name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  # Base depends
  - python=3.11
  - pip
  - matplotlib
  - numpy
  - pandas
  - scikit-learn

  - pip:
    # Pip-only installs
    - sphinx==6.2.1
    - sphinx-autoapi==3.0.0
    - https://github.com/revitron/revitron-sphinx-theme/archive/refs/tags/0.7.0.zip
